from datetime import timedelta
from feast import Entity, Feature, FeatureView, Field, FileSource, ValueType
from feast.types importFloat32, Int64, String

# Entities
driver = Entity(name="driver_id", join_keys=["driver_id"])
race = Entity(name="race_id", join_keys=["race_id"])

# Sources (using Parquet files generated by our extraction pipeline)
driver_stats_source = FileSource(
    path="data/driver_stats.parquet",
    timestamp_field="event_timestamp",
    created_timestamp_column="created_timestamp",
)

# Feature Views
driver_stats_view = FeatureView(
    name="driver_stats",
    entities=[driver],
    ttl=timedelta(days=3650), # Long TTL for historical stats
    schema=[
        Field(name="driver_elo", dtype=Float32),
        Field(name="driver_consistency", dtype=Float32),
        Field(name="driver_aggression", dtype=Float32),
        Field(name="races_finished_ratio", dtype=Float32),
    ],
    online=True,
    source=driver_stats_source,
    tags={"team": "analytics"},
)

# We can define more views for circuit stats, team stats, etc.
